<?php

return [

    'genesis_hash' => '0000000000000000000000000000000000000000000000000000000000000000',

    'geo_lookup_enabled' => env('AUDIT_GEO_LOOKUP_ENABLED', true),

    'sensitive_keys' => [
        'password', 'password_hash', 'password_confirmation',
        'mfa_secret', 'mfa_secret_temp', 'mfa_backup_codes',
        'token', 'remember_token', 'code', 'otp', 'verification_code',
        'secret', 'backup_codes', 'plainTextToken',
    ],

    'actions' => [
        'auth.login.success' => ['module' => 'auth', 'sensitive' => false],
        'auth.login.failed' => ['module' => 'auth', 'sensitive' => false],
        'auth.login.locked' => ['module' => 'auth', 'sensitive' => false],
        'auth.logout' => ['module' => 'auth', 'sensitive' => false],
        'auth.register' => ['module' => 'auth', 'sensitive' => false],
        'auth.mfa.setup_started' => ['module' => 'auth', 'sensitive' => false],
        'auth.mfa.otp_sent' => ['module' => 'auth', 'sensitive' => false],
        'auth.mfa.verify.success' => ['module' => 'auth', 'sensitive' => false],
        'auth.mfa.verify.failed' => ['module' => 'auth', 'sensitive' => false],
        'auth.mfa.enabled' => ['module' => 'auth', 'sensitive' => false],
        'auth.mfa.disabled' => ['module' => 'auth', 'sensitive' => true],
        'auth.mfa.backup_used' => ['module' => 'auth', 'sensitive' => false],
        'rbac.role.assigned' => ['module' => 'rbac', 'sensitive' => false],
        'rbac.role.revoked' => ['module' => 'rbac', 'sensitive' => false],
        'rbac.permission.assigned' => ['module' => 'rbac', 'sensitive' => false],
        'rbac.permission.revoked' => ['module' => 'rbac', 'sensitive' => false],
        'rbac.role.permissions_synced' => ['module' => 'rbac', 'sensitive' => false],
        'access.denied' => ['module' => 'security', 'sensitive' => false],
        'audit.view' => ['module' => 'audit', 'sensitive' => false],
        'audit.export' => ['module' => 'audit', 'sensitive' => false],
        'sis.student.enrolled' => ['module' => 'sis', 'sensitive' => false],
        'sis.portal.activated' => ['module' => 'sis', 'sensitive' => false],
        'academics.unit.created' => ['module' => 'academics', 'sensitive' => false],
        'academics.unit.updated' => ['module' => 'academics', 'sensitive' => false],
        'academics.unit.submitted' => ['module' => 'academics', 'sensitive' => false],
        'academics.unit.approved' => ['module' => 'academics', 'sensitive' => false],
        'academics.department.initialized' => ['module' => 'academics', 'sensitive' => false],
        'academics.department.ceo_approved' => ['module' => 'academics', 'sensitive' => false],
        'academics.program.curriculum_format_updated' => ['module' => 'academics', 'sensitive' => false],
        'academics.program.units_synced' => ['module' => 'academics', 'sensitive' => false],
        'academics.curriculum_version.created' => ['module' => 'academics', 'sensitive' => false],
        'academics.curriculum_version.submitted' => ['module' => 'academics', 'sensitive' => false],
        'academics.curriculum_version.registrar_approved' => ['module' => 'academics', 'sensitive' => false],
        'academics.curriculum_version.ceo_approved' => ['module' => 'academics', 'sensitive' => false],
        'academics.calendar.year_created' => ['module' => 'academics', 'sensitive' => false],
        'academics.calendar.semester_updated' => ['module' => 'academics', 'sensitive' => false],
        'admissions.application.confirmation_sent' => ['module' => 'admissions', 'sensitive' => false],
        'admissions.application.shortlist_email_sent' => ['module' => 'admissions', 'sensitive' => false],
        'admissions.application.status_email_sent' => ['module' => 'admissions', 'sensitive' => false],
        'admissions.application.portal_signup_email_sent' => ['module' => 'admissions', 'sensitive' => false],
        'admissions.application.staff_notified' => ['module' => 'admissions', 'sensitive' => false],
    ],

];
