<?php

return [

    'auth' => [
        'max_login_attempts' => 5,
        'lockout_minutes' => 15,
        'mfa_session_minutes' => 30,
        'mfa_enabled' => (bool) env('MFA_ENABLED', true),
        'mandatory_mfa_user_types' => ['staff', 'student', 'admin', 'external', 'super_admin'],
    ],

    'erp_registration' => [
        'invite_days' => (int) env('ERP_REGISTRATION_INVITE_DAYS', 14),
    ],

    'role_hierarchy' => [
        'Applicant' => 10,
        'Student' => 20,
        'Alumni' => 25,
        'Staff' => 30,
        'Lecturer/Tutor' => 40,
        'Admissions Officer' => 45,
        'HOD' => 50,
        'QA Officer' => 55,
        'HR Manager' => 60,
        'Finance Manager' => 65,
        'Academic Registrar' => 70,
        'Dean' => 75,
        'CEO' => 90,
        'Super Admin' => 100,
    ],

    'default_roles' => [
        'student' => 'Student',
        'staff' => 'Staff',
        'external' => 'Applicant',
        'admin' => 'Staff',
        'super_admin' => 'Super Admin',
    ],

    'permission_aliases' => [
        'dashboard.access' => 'core_manage_campuses_view',
        'admin.access' => 'core_manage_campuses_manage',
        'campuses.read' => 'core_manage_campuses_view',
        'campuses.manage' => 'core_manage_campuses_manage',
        'departments.read' => 'core_manage_departments_view',
        'departments.manage' => 'core_manage_departments_manage',
        'programs.read' => 'core_manage_programs_view',
        'programs.manage' => 'core_manage_programs_manage',
        'users.access.manage' => 'admin_manage_staff_manage',
        'admissions.read' => 'admin_manage_admissions_view',
        'admissions.write' => 'admin_manage_admissions_manage',
        'admissions.approve' => 'admin_manage_admissions_approve',
        'students.read' => 'admin_manage_students_view',
        'students.write' => 'admin_manage_students_manage',
        'academics.read' => 'academics_manage_units_view',
        'academics.write' => 'academics_manage_units_manage',
        'academics.approve' => 'academics_manage_units_approve',
        'academics.calendar' => 'core_manage_semesters_manage',
        'roles.assign' => 'admin_manage_staff_manage',
        'audit_logs.read' => 'core_manage_campuses_audit',
        'hr.read' => 'hr_manage_contracts_view',
        'hr.staff.view' => 'hr_manage_contracts_view',
        'hr.staff.create' => 'hr_manage_contracts_create',
        'hr.staff.edit' => 'hr_manage_contracts_edit',
        'hr.staff.delete' => 'hr_manage_contracts_manage',
        'hr.manage_contracts' => 'hr_manage_contracts_manage',
        'hr.manage_recruitment' => 'hr_manage_recruitment_manage',
        'hr.manage_leave' => 'hr_manage_leave_manage',
        'hr.manage_attendance' => 'hr_manage_attendance_manage',
        'hr.manage_performance' => 'hr_manage_performance_manage',
        'hr.manage_qualifications' => 'hr_manage_qualifications_manage',
        'hr.manage_licenses' => 'hr_manage_licenses_manage',
        'hr.manage_policies' => 'hr_manage_policies_manage',
        'finance.read' => 'finance_manage_student_accounts_view',
        'finance.fee_structures.manage' => 'finance_manage_fee_structures_manage',
        'finance.invoices.manage' => 'finance_manage_invoices_manage',
        'finance.payments.manage' => 'finance_manage_payments_manage',
        'finance.ledger.view' => 'finance_manage_chart_of_accounts_view',
        'site_settings.read' => 'site_settings_manage_settings_view',
        'site_settings.manage' => 'site_settings_manage_settings_manage',
        'qa.read' => 'qa_manage_plans_view',
        'administration.read' => 'administration_manage_registry_view',
        'procurement.read' => 'procurement_manage_suppliers_view',
        'research.read' => 'research_manage_projects_view',
        'ict.read' => 'ict_manage_helpdesk_view',
        'monitoring_evaluation.read' => 'monitoring_evaluation_manage_frameworks_view',
    ],

    /** Roles that may be assigned without a department (institution-wide). */
    'institution_wide_roles' => [
        'Super Admin',
        'CEO',
        'Academic Registrar',
        'Admissions Officer',
    ],

];
