<?php

return [

    /*
    | Platform modules shown on user dashboards. Each entry maps to an RBAC
    | permission gate; Super Admin can grant these via user/role assignment.
    */
    'modules' => [
        [
            'key' => 'dashboard',
            'label' => 'Dashboard',
            'description' => 'Personal landing page after sign-in.',
            'route' => 'dashboard',
            'permission' => 'dashboard.access',
            'category' => 'core',
            'scope' => 'institution',
        ],
        [
            'key' => 'admin_hub',
            'label' => 'Platform administration',
            'description' => 'Campuses, departments, users, and system configuration.',
            'route' => 'admin.index',
            'permission' => 'admin.access',
            'category' => 'core',
            'scope' => 'institution',
        ],
        [
            'key' => 'admissions',
            'label' => 'Approval dashboard',
            'description' => 'Verify, accept, and reject student onboarding applications by department.',
            'route' => 'administration.applications.index',
            'permission' => 'administration.read',
            'category' => 'admin',
            'scope' => 'department',
        ],
        [
            'key' => 'students',
            'label' => 'Student records (SIS)',
            'description' => 'Centralized 360° student biodata and enrolment records.',
            'route' => 'sis.dashboard',
            'permission' => 'students.read',
            'category' => 'admin',
            'scope' => 'department',
        ],
        [
            'key' => 'academics',
            'label' => 'Academics & curriculum',
            'description' => 'Course versioning, unit catalog, department mapping, and academic calendar.',
            'route' => 'departments.academics.dashboard',
            'permission' => 'academics.read',
            'category' => 'academics',
            'scope' => 'department',
        ],
        [
            'key' => 'academics_approvals',
            'label' => 'Application approvals',
            'description' => 'Review and approve onboarding applications for your academic department.',
            'route' => 'administration.applications.index',
            'permission' => 'administration.read',
            'category' => 'academics',
            'scope' => 'department',
        ],
        [
            'key' => 'finance',
            'label' => 'Finance',
            'description' => 'Fees, invoices, payroll, and procurement.',
            'route' => 'finance.dashboard',
            'permission' => 'finance.read',
            'category' => 'finance',
            'scope' => 'department',
        ],
        [
            'key' => 'hr',
            'label' => 'Human resources',
            'description' => 'Staff contracts, leave, and recruitment.',
            'route' => 'hr.dashboard',
            'permission' => 'hr.read',
            'category' => 'hr',
            'scope' => 'department',
        ],
        [
            'key' => 'administration',
            'label' => 'Administration',
            'description' => 'Institutional planning, budget approvals, admissions ops, compliance, and procurement visibility.',
            'route' => 'administration.dashboard',
            'permission' => 'administration.read',
            'category' => 'admin',
            'scope' => 'department',
        ],
        [
            'key' => 'qa',
            'label' => 'Quality assurance',
            'description' => 'QA plans, checklists, and compliance tracking.',
            'route' => 'qa.dashboard',
            'permission' => 'qa.read',
            'category' => 'qa',
            'scope' => 'department',
        ],
        [
            'key' => 'procurement',
            'label' => 'Procurement & logistics',
            'description' => 'Suppliers, purchase orders, and tenders.',
            'route' => 'procurement.dashboard',
            'permission' => 'procurement.read',
            'category' => 'finance',
            'scope' => 'department',
        ],
        [
            'key' => 'research',
            'label' => 'Research',
            'description' => 'Research projects, grants, and publications.',
            'route' => 'research.dashboard',
            'permission' => 'research.read',
            'category' => 'research',
            'scope' => 'department',
        ],
        [
            'key' => 'ict',
            'label' => 'Information & communication technology',
            'description' => 'Help desk, IT assets, infrastructure, and systems.',
            'route' => 'ict.dashboard',
            'permission' => 'ict.read',
            'category' => 'ict',
            'scope' => 'department',
        ],
        [
            'key' => 'monitoring_evaluation',
            'label' => 'Monitoring & evaluation',
            'description' => 'M&E frameworks, indicators, reporting, and follow-up.',
            'route' => 'monitoring_evaluation.dashboard',
            'permission' => 'monitoring_evaluation.read',
            'category' => 'admin',
            'scope' => 'department',
        ],
        [
            'key' => 'audit',
            'label' => 'Audit logs',
            'description' => 'Security and compliance activity trail.',
            'route' => 'admin.audit-logs.index',
            'permission' => 'audit_logs.read',
            'category' => 'security',
            'scope' => 'institution',
        ],
        [
            'key' => 'site_settings',
            'label' => 'Site settings',
            'description' => 'Public site identity, hero slides, contact details, and social links.',
            'route' => 'site-settings.index',
            'permission' => 'site_settings.read',
            'category' => 'core',
            'scope' => 'institution',
        ],
    ],

    'permission_aliases' => [
        'academics.read' => 'academics_manage_units_view',
        'finance.read' => 'finance_manage_student_accounts_view',
        'hr.read' => 'hr_manage_contracts_view',
        'qa.read' => 'qa_manage_plans_view',
        'administration.read' => 'administration_manage_registry_view',
        'procurement.read' => 'procurement_manage_suppliers_view',
        'research.read' => 'research_manage_projects_view',
        'ict.read' => 'ict_manage_helpdesk_view',
        'monitoring_evaluation.read' => 'monitoring_evaluation_manage_frameworks_view',
    ],

];
