<?php

return [

    'routes' => [
        'dashboard' => 'home',
        'admin.index' => 'dashboard',
        'admin.campuses.index' => 'building',
        'admin.department-groups.index' => 'layers',
        'admin.departments.index' => 'building-2',
        'admin.programs.index' => 'book-open',
        'admin.users.index' => 'users',
        'admin.roles.index' => 'shield',
        'admin.audit-logs.index' => 'scroll',
        'site-settings.index' => 'layers',
        'admissions.dashboard' => 'dashboard',
        'admissions.applications.index' => 'clipboard-list',
        'sis.students.index' => 'graduation-cap',
        'hr.dashboard' => 'dashboard',
        'finance.dashboard' => 'dashboard',
        'administration.dashboard' => 'dashboard',
        'administration.planning.index' => 'calendar',
        'administration.budget-aggregation.index' => 'layers',
        'administration.approvals.index' => 'clipboard-check',
        'administration.fund-distribution.index' => 'wallet',
        'administration.applications.index' => 'file-text',
        'administration.lifecycle.index' => 'refresh-cw',
        'administration.admission-packages.index' => 'mail',
        'administration.statutory.index' => 'file-text',
        'administration.inspection.index' => 'clipboard-check',
        'administration.procurement-pay.index' => 'briefcase',
        'administration.ledger-sync.index' => 'link',
        'qa.dashboard' => 'dashboard',
        'procurement.dashboard' => 'dashboard',
        'research.dashboard' => 'dashboard',
        'ict.dashboard' => 'dashboard',
        'ict.users.index' => 'users',
        'ict.roles.index' => 'shield',
        'hr.staff.index' => 'users',
        'hr.onboarding.index' => 'user-plus',
        'hr.contracts.index' => 'file-text',
        'hr.vacancies.index' => 'briefcase',
        'hr.recruitment.index' => 'user-search',
        'hr.leave.index' => 'clipboard-list',
        'hr.leave.overview' => 'clipboard-check',
        'hr.leave.employees' => 'users',
        'hr.payroll.index' => 'wallet',
        'hr.p9-forms.index' => 'file-text',
        'hr.policies.index' => 'shield-check',
        'hr.documents.index' => 'folder',
        'hr.offboarding.index' => 'log-out',
        'hr.training.index' => 'presentation',
        'departments.show' => 'layout-grid',
        'departments.academics.dashboard' => 'dashboard',
        'departments.academics.departments.index' => 'building-2',
        'departments.academics.units.index' => 'library',
        'departments.academics.programs.index' => 'book-open',
        'departments.academics.attendance-ledger.index' => 'clipboard-check',
        'departments.academics.clearance.index' => 'check-circle',
        'departments.academics.lesson-plans.index' => 'notebook',
        'departments.academics.lesson-plans.audit' => 'search',
        'departments.academics.performance.index' => 'bar-chart',
        'departments.academics.calendar.index' => 'calendar',
        'staff.dashboard' => 'dashboard',
        'employee.dashboard' => 'user',
        'employee.leave.index' => 'calendar-off',
        'employee.attendance.index' => 'clock',
        'portal.dashboard' => 'dashboard',
    ],

    'sections' => [
        'overview' => 'dashboard',
        'units' => 'book-open',
        'timetable' => 'calendar',
        'attendance' => 'clipboard-check',
        'grading' => 'award',
        'lesson-plans' => 'notebook',
        'content' => 'layers',
        'documents' => 'folder',
        'policies' => 'shield-check',
        'hod-management' => 'users-cog',
        'profile' => 'user',
        'application' => 'file-text',
        'enrolment' => 'badge-check',
        'academics' => 'graduation-cap',
        'finance' => 'wallet',
        'account' => 'lock',
    ],

    'default' => 'circle',

];
