<?php

return [

    /*
    | Assignable platform modules per department. Selecting a parent module
    | automatically grants all listed children (submodules) for that department.
    |
    | context: where the tool appears - hub (Academics dept), learning (schools
    | under Academics), operational (admin units), or any.
    */
    'modules' => [
        [
            'key' => 'admissions',
            'label' => 'Admissions & onboarding',
            'description' => 'Applicant intake, verification, and application approvals.',
            'permission' => 'admissions.read',
            'eligible_categories' => ['academic', 'administrative'],
            'children' => [
                [
                    'key' => 'admissions.dashboard',
                    'label' => 'Approval dashboard',
                    'description' => 'Verify, accept, and reject student onboarding applications.',
                    'permission' => 'admissions.read',
                    'route' => 'admissions.dashboard',
                    'context' => 'operational',
                ],
                [
                    'key' => 'admissions.applications',
                    'label' => 'Application approvals',
                    'description' => 'Review onboarding applications for this department.',
                    'permission' => 'admissions.read',
                    'route' => 'admissions.applications.index',
                    'params' => ['status' => 'pending'],
                    'context' => 'learning',
                    'group' => 'admissions',
                ],
            ],
        ],
        [
            'key' => 'students',
            'label' => 'Student records (SIS)',
            'description' => 'Centralized student biodata and enrolment records.',
            'permission' => 'students.read',
            'eligible_categories' => ['administrative'],
            'children' => [
                [
                    'key' => 'students.records',
                    'label' => 'Student Information System',
                    'description' => '360° student biodata and enrolment records.',
                    'permission' => 'students.read',
                    'route' => 'sis.dashboard',
                    'context' => 'operational',
                ],
                [
                    'key' => 'students.registrations',
                    'label' => 'Unit registrations',
                    'description' => 'Manage student unit registrations.',
                    'permission' => 'academics.read',
                    'route' => 'dashboard',
                    'context' => 'operational',
                    'coming_soon' => true,
                ],
            ],
        ],
        [
            'key' => 'academics',
            'label' => 'Academics & curriculum',
            'description' => 'Programmes, units, curriculum, calendar, and teaching delivery.',
            'permission' => 'academics.read',
            'eligible_categories' => ['academic', 'administrative'],
            'children' => [
                [
                    'key' => 'academics.curriculum_overview',
                    'label' => 'Curriculum overview',
                    'description' => 'Summary stats and quick links for programmes, units, and versions.',
                    'permission' => 'academics.read',
                    'route' => 'departments.academics.dashboard',
                    'context' => 'hub',
                ],
                [
                    'key' => 'academics.learning_profiles',
                    'label' => 'Learning department profiles',
                    'description' => 'Set curriculum profiles for schools under Academics.',
                    'permission' => 'academics.read',
                    'route' => 'departments.academics.departments.index',
                    'context' => 'hub',
                ],
                [
                    'key' => 'academics.unit_catalog',
                    'label' => 'Unit catalog',
                    'description' => 'Create and approve units before mapping them to programmes.',
                    'permission' => 'academics.read',
                    'route' => 'departments.academics.units.index',
                    'context' => 'hub',
                ],
                [
                    'key' => 'academics.programme_curriculum',
                    'label' => 'Programme curriculum',
                    'description' => 'Course length, intakes, semester mapping, and versioning.',
                    'permission' => 'academics.read',
                    'route' => 'departments.academics.programs.index',
                    'context' => 'hub',
                ],
                [
                    'key' => 'academics.calendar',
                    'label' => 'Academic calendar',
                    'description' => 'Configure academic years and intake terms.',
                    'permission' => 'academics.calendar',
                    'route' => 'departments.academics.calendar.index',
                    'context' => 'hub',
                ],
                [
                    'key' => 'academics.programmes',
                    'label' => 'Programmes',
                    'description' => 'Configure programmes, intakes, and unit mapping for this school.',
                    'permission' => 'academics.read',
                    'route' => 'departments.academics.programs.index',
                    'context' => 'learning',
                    'group' => 'education',
                ],
                [
                    'key' => 'academics.lesson_plans',
                    'label' => 'Lesson plans',
                    'description' => 'Create and manage lesson plans for allocated units.',
                    'permission' => 'academics.read',
                    'route' => 'dashboard',
                    'context' => 'any',
                    'coming_soon' => true,
                ],
                [
                    'key' => 'academics.attendance',
                    'label' => 'Attendance',
                    'description' => 'Session attendance and verification.',
                    'permission' => 'academics.read',
                    'route' => 'dashboard',
                    'context' => 'any',
                    'coming_soon' => true,
                ],
                [
                    'key' => 'academics.exams',
                    'label' => 'Exams & assessments',
                    'description' => 'Exam schedules, CAT marks, and results.',
                    'permission' => 'academics.read',
                    'route' => 'dashboard',
                    'context' => 'any',
                    'coming_soon' => true,
                ],
                [
                    'key' => 'academics.timetable',
                    'label' => 'Timetable',
                    'description' => 'Build and publish teaching timetables.',
                    'permission' => 'academics.read',
                    'route' => 'dashboard',
                    'context' => 'any',
                    'coming_soon' => true,
                ],
                [
                    'key' => 'academics.competencies',
                    'label' => 'Competencies',
                    'description' => 'Competency frameworks and assessments.',
                    'permission' => 'academics.read',
                    'route' => 'dashboard',
                    'context' => 'any',
                    'coming_soon' => true,
                ],
            ],
        ],
        [
            'key' => 'finance',
            'label' => 'Finance',
            'description' => 'Student finance, finance records, employee payroll, AR, AP, GL, budgeting, and treasury.',
            'permission' => 'finance.read',
            'eligible_categories' => ['administrative'],
            'children' => [
                [
                    'key' => 'finance.student_finance',
                    'label' => 'Student Finance',
                    'description' => 'Student accounts, fee structures, invoices, payments, receipts, adjustments, installment plans, refunds, clearance, and milestones.',
                    'permission' => 'finance.read',
                    'route' => 'finance.student-finance.hub',
                    'context' => 'operational',
                    'group' => 'finance',
                ],
                [
                    'key' => 'finance.records',
                    'label' => 'Finance Records',
                    'description' => 'General ledger, financial reports, accounts receivable/payable, budgeting, projects & donors, and treasury.',
                    'permission' => 'finance.read',
                    'route' => 'finance.records.index',
                    'context' => 'operational',
                    'group' => 'finance',
                ],
                [
                    'key' => 'finance.employee',
                    'label' => 'Employee Finance',
                    'description' => 'Payroll runs, payroll reports, statutory settings, and payroll-to-GL integration.',
                    'permission' => 'finance.read',
                    'route' => 'finance.employee.index',
                    'context' => 'operational',
                    'group' => 'finance',
                ],
                [
                    'key' => 'finance.ar',
                    'label' => 'Accounts Receivable (AR)',
                    'description' => 'Student invoices, outstanding balances, overdue invoices, payment allocation, receivable ageing and payment reminders.',
                    'permission' => 'finance.read',
                    'route' => 'finance.ar.index',
                    'context' => 'operational',
                    'group' => 'finance',
                ],
                [
                    'key' => 'finance.ap',
                    'label' => 'Accounts Payable (AP)',
                    'description' => 'Supplier accounts, supplier invoices, verification, approval, payment and the supplier ledger. Uses the three-way match.',
                    'permission' => 'finance.read',
                    'route' => 'finance.ap.index',
                    'context' => 'operational',
                    'group' => 'finance',
                ],
                [
                    'key' => 'finance.gl',
                    'label' => 'General Ledger (GL)',
                    'description' => 'Chart of Accounts, journal entries, debits, credits, account balances, Trial Balance, P&L, Balance Sheet and Cash Flow.',
                    'permission' => 'finance.read',
                    'route' => 'finance.gl.index',
                    'context' => 'operational',
                    'group' => 'finance',
                ],
                [
                    'key' => 'finance.budgeting',
                    'label' => 'Budgeting',
                    'description' => 'Annual, departmental and project budgets, budget requests, approvals and budget vs actual tracking. Uses the multi-tier approval.',
                    'permission' => 'finance.read',
                    'route' => 'finance.budgeting.index',
                    'context' => 'operational',
                    'group' => 'finance',
                ],
                [
                    'key' => 'finance.projects_donors',
                    'label' => 'Projects & Donors',
                    'description' => 'Donor profiles, project profiles, project budgets, donor invoices, donor disbursements, USD-to-KES conversion and donor accountability reports.',
                    'permission' => 'finance.read',
                    'route' => 'finance.projects-donors.index',
                    'context' => 'operational',
                    'group' => 'finance',
                ],
                [
                    'key' => 'finance.payroll_integration',
                    'label' => 'Payroll Integration',
                    'description' => 'Finance consumes approved payroll data from HR/Payroll (Workpay is the source of truth) and posts the matching accounting entries.',
                    'permission' => 'finance.read',
                    'route' => 'finance.payroll-integration.index',
                    'context' => 'operational',
                    'group' => 'finance',
                ],
            ],
        ],
        [
            'key' => 'hr',
            'label' => 'Human resources',
            'description' => 'Staff contracts, leave, recruitment, and performance.',
            'permission' => 'hr.read',
            'eligible_categories' => ['administrative'],
            'children' => [
                [
                    'key' => 'hr.dashboard',
                    'label' => 'HR dashboard',
                    'description' => 'Staff lifecycle overview, onboarding, and contract alerts.',
                    'permission' => 'hr.staff.view',
                    'route' => 'hr.dashboard',
                    'context' => 'operational',
                    'group' => 'hr',
                ],
                [
                    'key' => 'hr.staff',
                    'label' => 'Staff directory',
                    'description' => 'Employee master profiles and lifecycle records.',
                    'permission' => 'hr.staff.view',
                    'route' => 'hr.staff.index',
                    'context' => 'operational',
                    'group' => 'hr',
                ],
                [
                    'key' => 'hr.onboarding',
                    'label' => 'Onboarding',
                    'description' => 'Track new hire onboarding progress.',
                    'permission' => 'hr.staff.view',
                    'route' => 'hr.onboarding.index',
                    'context' => 'operational',
                    'group' => 'hr',
                ],
                [
                    'key' => 'hr.contracts',
                    'label' => 'Contracts',
                    'description' => 'Employment contracts, renewals, and expiry alerts.',
                    'permission' => 'hr.manage_contracts',
                    'route' => 'hr.contracts.index',
                    'context' => 'operational',
                    'group' => 'hr',
                ],
                [
                    'key' => 'hr.vacancies',
                    'label' => 'Vacancies',
                    'description' => 'Job openings and recruitment.',
                    'permission' => 'hr.manage_recruitment',
                    'route' => 'hr.vacancies.index',
                    'context' => 'operational',
                    'group' => 'hr',
                ],
                [
                    'key' => 'hr.recruitment',
                    'label' => 'Recruitment',
                    'description' => 'Review applications, shortlist, and offers.',
                    'permission' => 'hr.manage_recruitment',
                    'route' => 'hr.recruitment.index',
                    'context' => 'operational',
                    'group' => 'hr',
                ],
                [
                    'key' => 'hr.payroll',
                    'label' => 'Payroll',
                    'description' => 'Staff payroll, statutory deductions, and KRA tax bands.',
                    'permission' => 'hr.manage_contracts',
                    'route' => 'hr.payroll.index',
                    'context' => 'operational',
                    'group' => 'hr',
                ],
            ],
        ],
        [
            'key' => 'portal',
            'label' => 'Portal & communications',
            'description' => 'Website content, events, blog, and gallery.',
            'permission' => 'dashboard.access',
            'eligible_categories' => ['administrative', 'support'],
            'children' => [
                [
                    'key' => 'portal.content',
                    'label' => 'Portal content',
                    'description' => 'Manage public portal pages and content.',
                    'permission' => 'dashboard.access',
                    'route' => 'dashboard',
                    'context' => 'operational',
                    'coming_soon' => true,
                ],
                [
                    'key' => 'portal.events',
                    'label' => 'Events',
                    'description' => 'Campus events and announcements.',
                    'permission' => 'dashboard.access',
                    'route' => 'dashboard',
                    'context' => 'operational',
                    'coming_soon' => true,
                ],
                [
                    'key' => 'portal.blog',
                    'label' => 'Blog & gallery',
                    'description' => 'News articles and photo gallery.',
                    'permission' => 'dashboard.access',
                    'route' => 'dashboard',
                    'context' => 'operational',
                    'coming_soon' => true,
                ],
            ],
        ],
        [
            'key' => 'qa',
            'label' => 'Quality assurance',
            'description' => 'QA plans, checklists, and compliance tracking.',
            'permission' => 'dashboard.access',
            'eligible_categories' => ['administrative', 'support'],
            'children' => [
                [
                    'key' => 'qa.plans',
                    'label' => 'QA plans',
                    'description' => 'Quality assurance planning and reviews.',
                    'permission' => 'dashboard.access',
                    'route' => 'dashboard',
                    'context' => 'operational',
                    'coming_soon' => true,
                ],
                [
                    'key' => 'qa.compliance',
                    'label' => 'Compliance',
                    'description' => 'Regulatory compliance and corrective actions.',
                    'permission' => 'dashboard.access',
                    'route' => 'dashboard',
                    'context' => 'operational',
                    'coming_soon' => true,
                ],
            ],
        ],
    ],

    /** Default top-level modules when creating departments by category. */
    'category_defaults' => [
        'academic' => ['academics', 'admissions'],
        'administrative' => [],
        'support' => [],
    ],

    /** Backfill mapping from legacy dept_code values. */
    'legacy_dept_code_modules' => [
        'HR' => ['hr'],
        'FIN' => ['finance'],
        'PRC' => ['finance'],
        'ACAD' => ['academics'],
        'ADM' => ['admissions'],
        'SIS' => ['students'],
        'RES' => ['portal'],
        'ICTO' => ['portal'],
        'MKT' => ['portal'],
    ],

    /** Map dashboard permission keys to assignable department module keys. */
    'dashboard_permission_modules' => [
        'admissions.read' => 'admissions',
        'students.read' => 'students',
        'academics.read' => 'academics',
        'finance.read' => 'finance',
        'hr.read' => 'hr',
        'dashboard.access' => 'portal',
        'audit_logs.read' => null,
        'admin.access' => null,
    ],

];